"""Build seamless launch/ambient loops, with explicit source attribution."""
import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/"Shared"))
from project_paths import PROJECT_ROOT, ART_ROOT

from pathlib import Path
import sys,urllib.request,json,hashlib
ROOT=PROJECT_ROOT
sys.path.insert(0,str(ROOT/'Saved/ToolDependencies'))
import numpy as np
import soundfile as sf

OUT=ART_ROOT/'Audio';OUT.mkdir(parents=True,exist_ok=True)
url='https://www.nasa.gov/wp-content/uploads/2015/01/590189main_ringtone_131_launchNats.mp3'
source=OUT/'NASA_STS131_launch.mp3'
if not source.exists():source.write_bytes(urllib.request.urlopen(url,timeout=60).read())
data,rate=sf.read(source,always_2d=True);mono=data.mean(axis=1)
print('NASA_AUDIO',rate,len(mono)/rate,'seconds')
# The central roar avoids the onset and gives a stable bed for real-time thrust mixing.
start=int(len(mono)*.32);length=min(int(rate*9),len(mono)-start)
clip=mono[start:start+length].copy();clip-=clip.mean()
def loop(x,fade):
    n=min(fade,len(x)//4);t=np.linspace(0,1,n,endpoint=False)
    joined=x[-n:]*(1-t)+x[:n]*t
    return np.concatenate((joined,x[n:-n]))
clip=loop(clip,int(rate*.5));clip*=.76/max(np.max(np.abs(clip)),1e-6)
sf.write(OUT/'EngineRoar.wav',clip,rate,subtype='PCM_16')

# Original, deterministic coastal wind bed. No third-party music or voice.
rate=48000;length=rate*18;rng=np.random.default_rng(20260908)
freq=np.fft.rfftfreq(length,1/rate)
def noise(channel):
    spectrum=np.fft.rfft(rng.normal(size=length))
    band=(freq/(freq+60))*np.exp(-freq/4200)/np.maximum(freq,60)**.55
    result=np.fft.irfft(spectrum*band,n=length)
    t=np.arange(length)/rate
    result*=.55+.2*np.sin(t*2*np.pi/9+channel)+.12*np.sin(t*2*np.pi/6)
    result=loop(result,rate)
    return result*.3/max(np.max(np.abs(result)),1e-6)
sf.write(OUT/'CoastalWind.wav',np.stack([noise(0),noise(.8)],axis=1),rate,subtype='PCM_16')
manifest={'engine_source':url,'credit':'NASA / Discovery STS-131: Sound of Launch','source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'source_page':'https://www.nasa.gov/historical-sounds/','usage':'https://www.nasa.gov/nasa-brand-center/images-and-media/','adaptation':'Extracted central roar, mono mix, DC removal, half-second loop crossfade and peak normalization. This is a sound-design bed, not a recording of the simulated vehicle.','ambient':'Original deterministic filtered-noise coastal wind generated by prepare_scene_audio.py.'}
(OUT/'CREDITS.json').write_text(json.dumps(manifest,indent=2),encoding='utf-8')
for path in OUT.glob('*.wav'):
    a,sr=sf.read(path);assert np.isfinite(a).all() and np.max(np.abs(a))<.99
    print(path.name,'duration',len(a)/sr,'peak',float(np.max(np.abs(a))))
